name: CMake

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install MSVC compiler
      uses: ilammy/msvc-dev-cmd@v1
      with:
        toolset: 14.2
        arch: x64

    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@v1.1

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 6.2.0
        arch: win64_msvc2019_64
        aqtversion: ==1.2.2

    - name: Build and Install
      run: |
        mkdir build; cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=../installed \
          -DALL_PLUGINS=ON \
          -GNinja
        cmake --build .
        cmake --install .

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: QvPlugin-${{ runner.os }}.zip
        path: installed/
